version: "3.3"

services:
  app:
    container_name: specification-postgres
    image: specification-postgres
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres-server
  postgres-server:
    image: server-specification
    build:
      context: ./utils
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=server
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    volumes:
      - /var/lib/postgresql/data